name: Sanity Check

on:
  push:
    branches: ["redux-chat-2023"]
  pull_request:
    branches: ["redux-chat-2023"]
permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Packages
        run: |
          npm install

      - name: Lint check
        run: |
          npm run lint

      - name: Test check
        run: |
          npm run test
